# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 07:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSignUp', '0003_notesdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdatabase',
            name='sharedwith',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
