# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSignUp', '0004_notesdatabase_sharedwith'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myTag', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='notesdatabase',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='myNote',
            field=models.ManyToManyField(to='UserSignUp.NotesDatabase'),
        ),
    ]
