# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSignUp', '0005_auto_20170606_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharednames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareduser', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='notesdatabase',
            name='sharedwith',
        ),
        migrations.AddField(
            model_name='sharednames',
            name='mysharedname',
            field=models.ManyToManyField(to='UserSignUp.NotesDatabase'),
        ),
    ]
